### ISSUE TITLE
Try to provide stripped runtime for editor to make scene view reload more quickly

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#100]
编辑器用的版本，不需要包含 canvas 的渲染代码，请测试一下去掉后能减小多少代码，对加载时间的影响有多大? 如果同时将脚本编译为 min 版本，会进一步加快加载速度吗？

加载时间可用这种方式统计：
<img width="526" alt="2015-07-17 11 16 20" src="https://cloud.githubusercontent.com/assets/1503156/8739998/6a64469e-2c75-11e5-98ee-9020bc3cbd77.png">

**Comment by jareguo** [comment]
目前 scene view 的瓶颈在 cocos 上，除了 evalulate 的时间，还有 load 进来的时间 (50ms, 这个应该可以用 min 版本进行优化)，cc.setup 的执行时间 (200+ms)
将来还可以考虑在后台预热一个 webview 的方式进行彻底优化，不过哪怕是那样尽量减小开销也是值得的。

**Comment by 2youyouo2** [comment]
- origin cocos2d-html.js (modules: all)
    - 3.5 M
    - 390 ms (evaluate time)
    - 190 ms (setup time )
   - origin cocos2d-html.min.js (modules: all)
    - 1.9 M
    - 350 ms (evaluate time)
    - 190 ms (setup time)
   - stripped cocos2d-html.js (modules: 'core', 'particle', 'ccui', 'shaders')
    - 2.6 M
    - 216 ms (evaluate time)
    - 190 ms (setup time)
   - stripped cocos2d-html.min.js (modules: 'core', 'particle', 'ccui', 'shaders')
    - 918 kb
    - 170 ms
    - 190 ms (setup time)

**Comment by jareguo** [comment]
感谢凯乐的测试，从结果可以看出，减少 cocos 加载的模块能大幅提升加载性能，但我们目前没办法帮用户做出选择。
我们现在能够确认的是使用 min 版本会进一步加快加载速度，但是效果不是很明显，等双 webview 这种非常规手段做完再来考虑压榨这里的性能吧。

**Comment by pandamicro** [comment]
我的建议是可以注入moduleConfig.json，在打包前替换moduleConfig.json文件（注入的方式是为了避免修改引擎）。使用定制版的，里面可以删除很多不必要的东西比如actions模块中的：CCActionCamera.js，CCActionCatmullRom.js，CCActionTween.js

再比如ccui中不需要的一些控件或者布局类。

最终Cocos希望能够更彻底得实现模块化，可以真正做到需要什么加载什么

**Comment by jareguo** [comment]
@pandamicro 先别走…… 这些删掉的东西普通用户用到的机率大吗？这部分我们是不是允许用户任意配置？例如
```js
{
  引擎路径: {
    编辑器版: ~/.../cocos2d.editor.js,
    发布测试版: ~/.../cocos2d.publish.js,
    发布压缩版: ~/.../cocos2d.publish.min.js
  }
}
```

**Comment by pandamicro** [comment]
抱歉，最近邮件太多，有些漏掉的，:-p

列出来的几个CCActionCamera.js，CCActionCatmullRom.js，CCActionTween.js，都是普通用户不会用到的。还有很多TransitionScene之类的东西

因为在考虑引擎的模块化，所以暂时不打算做其他大的调整，其实你们可以用定制的直接替换，影响不大

**Comment by jareguo** [comment]
多谢 @pandamicro 
@2youyouo2 能否先把 panda 说的那些东西去掉？

**Comment by 2youyouo2** [comment]
不能确定用户到底需要哪些模块的情况下，目前编辑器里面还是给full version吧。
在后续编辑器可以提供让用户选择需要哪些文件进行打包来精简包大小。
