### ISSUE TITLE
Provide examples for cocos user

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#101]
https://github.com/fireball-x/example-cocos2d-js
请在这个 repo 里提交 example，每个 example 就是一个可运行的 Scene，用于介绍一个特定功能（如 Button, Sprite, Particle, BMFont...）
补全范例后再请 @nantas 帮忙整合到 api 和 dashboard 中。

**Comment by nantas** [comment]
https://github.com/fireball-x/example-cocos2d-js

目前完成的范例：

- sprite action
- sprite animation
- keyboard input
- ease movement
- update movement
