### ISSUE TITLE
should we use the camelCase naming rule for the key in package.json?

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#102]
@jwu @nantas 
按照国际命名规则，package.json 里面的【变量名】采用的都是驼峰命名法，例如：
```js
{
  devDependencies: {
    xxx: xxx,
    yyy: yyy,
  },
  engineStrict: true,
  preferGlobal: ...,
  publishConfig: ...
}
```
事实上不单单是 package.json，yuidoc, bower 的 json 都是采用驼峰命名法。

结果我们采用了另外一种很反人类的写法，全是横杠：
```js
{
  engine-version: ...,
  shared-packages: true,
  native-modules: ...
}
```

这样两种风格同时出现，感觉很不规范。而且代码里面取值的时候，一会要用点，一会要用查字典，太奇怪了（`package.build["scripts-dev"]`）

PS:
如果你们问我，那为毛人家 dependencies 里面的包名，也是很多横杠（coffee-script 什么的）？
那是因为在这里这个 key 实际上是做为 value 来用的，不是【变量名】。我的观点是逻辑就应该遵守语言命名规范，数据爱叫什么没关系。

**Comment by jwu** [comment]
agree

**Comment by jwu** [comment]
@nantas please confirm this.
