### ISSUE TITLE
Fireball 0.5 beta changelist

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#106]
## Big Changes

 - 升级 Electron 到 0.30.0
 - 支持 ES6 语法

## Editor Framework

 - 修复了 droppable 不能嵌套使用的问题

## Asset DB

 - 将 `uuid://` 的注册从 Canvas-Studio 转移到 AssetDB, 这样让用户可以更方便的在 Editor Framework 中使用 AssetDB 和 Assets Panel 
 - 支持在 Fireball 外删除和添加 assets, 在回到 Fireball 后会自动检测并更新这些 assets

## Canvas Studio

 - 加入 Build Project 面板
 - 调整了 Hierarchy 注册 menu 的流程
 - 加入 Hierarchy 右键菜单
 - 加入 Help 菜单
 - 加入 About 菜单
 - 加入了屏幕辅助框的绘制
 - 改进 Inspector 加载策略, 现在在 Assets 或者 Hierarchy 中快速滑动, 也不会出现卡顿的现象.
 - 添加, 删除和移动子节点将不会改变他的位置
 - 修复了多次点击 Scene Panel 的 reload 按钮会报错的问题
 - 修复了点击 Open Project 菜单报错的问题
 - 修复刷新其他窗口的页面会导致主窗口的 Hierarchy 选中的节点失去选择

**Comment by jwu** [comment]
@jareguo @2youyouo2 @nantas @w88975 beta 期间 ( 2015.07.20 - 2015.07.25 ) 请根据自己的改动添加评论并维护. 我会在 beta 发布前对评论中的改动做收集, 并反馈到最终发布的 changelist 中.

**Comment by 2youyouo2** [comment]
Plist atlas import for sprite animation #115

**Comment by jareguo** [comment]
- Engine
    - Support wrapper attribute for FireClass (fireball-x/fireball#127)
    - Add NodeWrapper.canHaveChildrenInEditor to mark the wrapper of BitmapFont as sealed leaf for hierarchy panel (fireball-x/fireball#113)
- Canvas Studio
    - Add building pipeline (fireball-x/fireball#70)

**Comment by w88975** [comment]
- Canvas Studio
  - add fire-about page (https://github.com/fireball-x/fireball/issues/125)
  - add help Menu item (https://github.com/fireball-x/fireball/issues/124)
  - add slidable with ui-property (https://github.com/fireball-packages/ui-property/pull/3)

**Comment by nantas** [comment]
- Editor
  - Add metrics script and library to index html of canvas-studio and dashboard (#31)
