### ISSUE TITLE
hierarchy move item get wrong order

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#112]
This can be 100% reproduce by following the step:

1. create 3 item as:

```
001
002
003
```

2. move 003 before 001:

```
003
001
002
```

3. move 003 into 001:

```
001
  |- 003
002
```

4. drag 003 after 002:

it should be:

```
001
002
003
```

**But what we get is:**

```
003
001
002
```

**Comment by jareguo** [comment]
请 @2youyouo2 改一下，在最后一步设置时，当 Fire.node(003).parent 被重新赋值后，没有把 003 放到 parent 的最后一个节点。
