### ISSUE TITLE
Should mark BitmapFontWrapper as leaf for hierarchy panel

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#113]
对于不能增加子节点的 wrapper，应该有这样一个标记，否则 hierarchy 操作时会对用户造成很大不便。

**Comment by jwu** [comment]
用户在 Hierarchy 中移动节点, 如果遇到 Leaf 节点, 将会将本次移动标记为 invalid 并在移动过程中显示为红色. 但是该操作仍然会将信息发送到 webview 中, 由 Runtime 负责错误处理.

**Comment by jareguo** [comment]
@jwu 在 query-hierarchy 拿到的数据里，加入了 canHaveChildren 属性，请用在 addItem 的时候通过 `if ( entry.canHaveChildren === false )` 进行判断。
