### ISSUE TITLE
wrong position for child

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#114]
When I create two sprite, and set one as child of another. Then set the child's local position to [0,0], you will find child moved to bottom-left of the parent. It should moved to the center of the parent by default. Or let's say it should consist with the parent's gizmos position.

**Comment by jareguo** [comment]
这个应该不是坐标的问题，因为你拿 world position 的结果还是对的，只是渲染错了。
@2youyouo2 你能进一步解释一下吗？

**Comment by nantas** [comment]
Not only for child nodes, I have a sprite at root level with script like this:

```js
module.exports = Fire.Class({
    constructor: function() {
        cc.view.setDesignResolutionSize(640, 320, cc.ResolutionPolicy.SHOW_ALL);
        cc.view.resizeWithBrowserSize(true);
    }
});
```

This will cause wrong render position of sprite in scene:
![image](https://cloud.githubusercontent.com/assets/344547/8765225/993e3c24-2e35-11e5-9d27-c608f8e59c4b.png)

**Comment by jareguo** [comment]
楼上这个问题，应该是因为 grid 的坐标算错了，没有应用 cocos 的缩放策略导致。

**Comment by 2youyouo2** [comment]
cocos 里面子的世界坐标 是以父亲的左下点世界矩阵来计算的，他没有算上父亲的锚点位置
这是cocos的内部计算方式没法改变

**Comment by jareguo** [comment]
这是 cocos 的 feature，不是 bug
