### ISSUE TITLE
basic dev environment

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#12]
I've finish the basic environment for establish the project. However this is done in shell script. Please add npm scripts to help developer ease the tasks

**Comment by jwu** [comment]
new task: `check-deps`

After discuss with @jareguo , we agree the package.json and bower.json under fireball/ should not use auto-merge. Instead, it will run a checking task and raise warning for several cases. Here is the step:

 - load every sub-modules's package.json, compare the dependencies and devDependencies with the main package.json
   - if main package.json missing dependencies that exists in sub-modules, report warning message about it
   - if any of the package.json (including main and sub-mobules) using a different version of the module, report the version of each one.
- load every sub-modules's bower.json, compare the dependencies and devDependencies with the main bower.json
  - The compare rule is same as package.json

When a warning raised, 
 - if it is missing of the modules in main repo, ask @jwu to add it and commit a new version.
 - If it is a different version among main and sub-modules
   - if it is main repo not updated, do it by @jwu.
   - if it is differences among sub-modules, find the maintainers in charge of it, let them discuss, unit-test themselves and agree with a version of the module for fireball.

**Comment by jwu** [comment]
I add runtime support for dashboard, and this needs us update our working pipeline again. The runtime update work flow is similar to builtin package workflow. Each fold in runtime is a git repo that we clone from `fireball-x/runtime-{name}`, we need to manually register the runtime in our working pipeline so that before it can clone or update from git.

**Comment by jwu** [comment]
current support runtime:

 - runtime-cocos2d-js
 - runtime-pixi

**Comment by nantas** [comment]
runtime install and update task added,
also included in `gulp bootstrap` and `gulp update` workflow.
