### ISSUE TITLE
Help menu

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#124]
Help

 - Documentation
 - Discussion Group
 - Report Issue...
 - Subscribe Newsletter
 - About

@nantas , would you mind to provide the link of these menu items directly here?

**Comment by nantas** [comment]
- Docs: http://docs.fireball-x.com/
- Discussion Group: http://fireball-x.com/chat (need to be created)
- Report Issue: https://github.com/fireball-x/fireball/issues/
- Subscribe: http://eepurl.com/bh5w3z
