### ISSUE TITLE
Support node type in inspector

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#127]
@jareguo will provide `wrapper:` key word in properties. I should use `<fire-node>` for it. Also the type name display in `fire-node` should use its shortname. e.g. `Fire.Runtime.NodeWrapper => node`

**Comment by jareguo** [comment]
已提交，现在可以这样声明
```
            leg: {
                default: null,
                wrapper: cc.spine.skeleton,
            }
```
我会自动转换成为
```
            leg: {
                default: null,
                type: SkeletonWrapper,
            }
```

另，用户仍然要调用 `this.leg.targetN` 才能拿到真正的 skeleton，因此建议 shortname 显示为 "SkeletonWrapper" 而不是 "Skeleton" 以示区别。
