### ISSUE TITLE
The basic dashboard interface

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#14]
The basic interface for dashboard

**Comment by jwu** [comment]
@nantas I've finish the basic interface for dashboard. Most function still not implement, but it is ok and will not block designer refine the structure. Please create a new task to beauty the dashboard.

**Comment by jwu** [comment]
BTW: the New Project still lake of design, let me known if any update.

**Comment by nantas** [comment]
New project view:

![image](https://cloud.githubusercontent.com/assets/344547/7999223/6c437d98-0b7a-11e5-8e30-bf79a57aaf3a.png)

Project Template view:

![image](https://cloud.githubusercontent.com/assets/344547/7999295/7bb6f3da-0b7b-11e5-8871-9d9648a024ca.png)


I'd like to combine project name and project path to a single text field, the last part of the project path will be used as project name in settings file. @jwu

**Comment by jwu** [comment]
Tasks:
  - [ ] Allow new project page navigate by index
  - [ ] path/to/project should return a path that **never** exists before create button clicked
  - [ ] after browse, a `path/to/` value send back, and input field to show `path/to/New Project`, and keep the New Project highlight and selected for editing.
