### ISSUE TITLE
Support loading from raw assets in engine-framework

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#140]
提供一个接口，用来让用户获得 raw file 的实际加载路径。
接口形如：
```
Fire.url('raw://foo');
Fire.raw('foo/bar.atlas');
Fire.raw + 'foo/bar.atlas';
```

`Fire.url('raw://foo');` 看起来很优雅，好处是将来可以加入其它 protocol，这样用户可以用一种方式处理所有 protocol。但如果我们不能提供给用户更多的 protocol，这个接口就是用户的负担，用户必须写很多协议的拼装代码才行（`"raw://" + path`）。
```
var preloadAssets = ...;    // read from anywhere
var paths = preloadAssets.map(function (path) {
    return Fire.url('raw://' + path);
});
```

`Fire.raw('foo/bar.atlas');` 能帮用户省去协议拼装操作，看起来一样很清爽。但用户如果不看文档，可能不能理解这个接口做了什么。他有可能认为我们会将路径神奇的处理成 `.../raw/00/45423154646.atlas`，一定要用这个接口 cocos 才能加载得到东西，那么那些 cocos 内部需要关联加载的文件怎么办？

`Fire.raw + 'foo/bar.atlas';` 是最直白的，避免了以上所有问题，也是我觉得用得最爽的接口。

**Comment by 2youyouo2** [comment]
Fire.url.raw 呢？

**Comment by jareguo** [comment]
能具体解释下吗？

**Comment by 2youyouo2** [comment]
比如可以 写成这样 Fire.url.raw('foo/bar.atlas')
像Fire.raw，但是再加一个url 前缀可以明确一些这个接口是干什么的

或者 Fire. protocol.raw('foo/bar.atlas') ?

**Comment by nantas** [comment]
`Fire.raw + 'foo/bar.atlas'`
和
`Fire.url.raw('foo/bar.atlas')`
我都可以接受

**Comment by jwu** [comment]
Agree with nantas

**Comment by 2youyouo2** [comment]
Fire.raw + 'foo/bar.atlas' 
可能会涉及到 让用户判断到底 Fire.raw 有没有 在最后加 '/' 分隔符
用接口形式可以帮助处理这些情况

**Comment by jareguo** [comment]
OK, 那就用 `Fire.url.raw('foo/bar.atlas');`，这样以后接口也容易进一步扩展

**Comment by jareguo** [comment]
raw 方案暂时不加

**Comment by jareguo** [comment]
虽然 raw 方案被 simple asset 替代了，但是仍然有同样的需求。

**Comment by jareguo** [comment]
@nantas 已加上，现在可以这样用
```js
Fire.url.raw('SmallSun.plist');
// "/Users/jareguo/firebox/game-duang-sheep/assets/SmallSun.plist" in editor
```

**Comment by nantas** [comment]
`Fire.url.raw(path)` 这里的 path 是相对于`assets`目录的 path 吗？还是某个特定关键字文件夹下的路径？

**Comment by jareguo** [comment]
是相对于 assets 目录的
