### ISSUE TITLE
提供一种方式获取编辑器中设置的 design resolution

### ISSUE THREAD

**Issue by 2youyouo2** [fireball-x/fireball#166]
用来在init runtime 时 设置runtime design resolution

**Comment by jareguo** [comment]
请 @jwu 在 build 时提供该分辨率，在 engine.init 时传入该分辨率，在分辨率改变时重设 Fire.engine.designResolution

**Comment by jwu** [comment]
@jareguo 已经在 builder 中加入 preview resolution 的选项. 并且他会在 `app:build-project` 消息中传入 `previewWidth` 和 `previewHeight` 这两个属性. 请根据修改调整代码
