### ISSUE TITLE
Sprite visual size not reflecting sprite size

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#167]
If you change a sprite's `visual` size value in inspector, only the size of the blue box around sprite changes, not the sprite renderer.

It's hard to get the actual pixel size of sprite at the moment.

**Comment by nantas** [comment]
after discussion, we agree to make the size property `readonly` in inspector.

**Comment by 2youyouo2** [comment]
need #169 be completed

**Comment by 2youyouo2** [comment]
finished, now size is readonly
