### ISSUE TITLE
"Simple" asset solution

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#171]
Before we can work out each asset type runtime supports, we should provide a "simple" asset solution as the default asset workflow for users:

- simple asset only store uuid to url mapping
- user is responsible for interpret asset by using it with the correct api

Once this is done, we'll be able to import any asset type for cocos2d-js.

**Comment by jareguo** [comment]
@jwu 考虑新增一个类型 `Fire.RawAsset`，用来做为所有 Asset 的基类，所有 cocos 的 asset 都继承自这个类。

Fire.RawAsset 不会被实例化，所有属性都是静态方法，接口有：
- validateAsset (原 Fire.Asset 静态方法，现在定义在 Meta 中)
- icon (现在定义在 meta 中)
- createNode

其中 validateAsset 和 icon 现在定义在 Meta 中，建议挪到这里，这样新增资源类型时才不用注册 Meta。除了这些给编辑器用的方法，Fire.RawAsset 还能用在属性 `url: xxx` 里，用来限制 Inspector 能够拖动的资源类型，所以 Fire.RawAsset 会进入到 build 里面。

现有的 Fire.Asset 也继承自 Fire.RawAsset。Fire.Asset 允许实例化和序列化，是 CustomAsset, Scene, Prefab 等类型的基类。

**Comment by jareguo** [comment]
经过确认，现在的 AssetDB 引入 Asset 改动较大，目前仍然先要求 simple asset 也注册 meta。

**Comment by jareguo** [comment]
引入 simple asset 概念后，用户不需要再困扰资源应该定义成 [url](https://github.com/fireball-x/fireball/issues/137) 还是 type 了。因为我们只要把规定简化为： simple asset 一定拿的是 url，普通 asset 一定拿的是 Fire Asset。

但是为了使代码保持清晰，目前仍然要求 simple asset 由 url 声明，fire asset 由 type 声明，否则给予警告。

**Comment by nantas** [comment]
Simple asset dragged into property will be cleared when reselect node.
property definition: 
```js
    properties: {
        tilemapAsset: {
            default: "",
            url: Fire.RawAsset
        }
    },
```

asset meta:
```js
{
  "ver": 0,
  "uuid": "b3502692-2943-4363-97c9-9f5591aaae5f",
  "asset-type": "asset"
}
```

**Comment by jareguo** [comment]
已修复，但现在 Inspector 还拖不了，要等 #187
