### ISSUE TITLE
Built game not working on mobile devices

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#173]
```js
 cc.Sprite.WebGLRenderCmd = function (renderable) {
        cc.Node.WebGLRenderCmd.call(this, renderable);
        this._needDraw = true;
        this._quad = new cc.V3F_C4B_T2F_Quad();
        this._quadWebBuffer = cc._renderContext.createBuffer();
        this._quadDirty = true;
        this._dirty = false;
        this._recursiveDirty = false;
    };
```
From first impression, webgl related code not initialized.
The `cc-config.js` file put `renderMode: 0` (auto) so let's find out why:

- [x] it's not using canvas mode on android device
- [x] the webgl related code not initialize on ios device

**Comment by 2youyouo2** [comment]
@jareguo engine-extends.js 里面有这句 
sceneName.endsWith('.fire')

safari 的string里面没有endsWith的实现，导致报错

**Comment by nantas** [comment]
可以在 build-engine 这个任务里加入 babel 相关的处理

**Comment by jareguo** [comment]
已修正，之后会把 endsWith 加入到engine-framework/src/polyfill 里面
