### ISSUE TITLE
should not use absolute path in meta importer

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#177]
类似 copyRawfileToLibrary 这样的 api 不应该接收绝对路径，否则用户有可能将资源 import 到 library 外面，也可能跟别的 import 好的文件重名。
这里用户只需要提供文件名，由 asset db 自动选择合适的路径存放。

多说一句，这里的 raw file 还是应该像原来 #58 那样讨论的就好了，现在改成这样有几个问题：
- 用户需提供 dests 定义，这样逻辑上和 import 存在冗余。而且真要帮用户校验的话只校验文件名是不够的。
- 文件名被改成 {uuid}.xxx 了，失去了 raw file 的意义，而且万一有多个 raw file 的后缀名相同咋办？

**Comment by jwu** [comment]
我觉得这种类型的 rawfile 使用已经超出了 asset-db 的设计了. 既然是 rawfile , 应该要去读他的源文件而不是读 copy 到 `library/imports/` 目录下的文件.

**Comment by jareguo** [comment]
但是现在 TTF 就是有这样的需求，说白了就是你是否允许 custom asset 自带 raw file。

**Comment by jwu** [comment]
ttf 的需求是一份 .json + 一份 .ttf 文件, 我觉得如果设计的足够好的话, 应该是需要做到 .json 文件去读 rawfile 地址的. 这样我们就不需要吧 .ttf 拷贝过去.
