### ISSUE TITLE
Duplicate node in scene

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#179]
User should be able to duplicate node in scene by:

- press `ctrl/cmd + D` 
- from hierarchy context menu

Duplicated node should have:

- same mixin and data values
- share the same parent with original node
- put under the original node in hierarchy view

Please give me a raw estimation on when this feature can be expected, if it's not possible to be done quickly.

**Comment by jareguo** [comment]
今天才看到最后一句，今天会把这个功能做完
