### ISSUE TITLE
particle attach node have several problems

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#182]
1. delete particle will not destroy its gizmos
1. attach particle to other node will make it not playing

**Comment by jareguo** [comment]
这是因为删除节点后，经过了异步 ipc 处理时，已经无法再使用 id 拿到对应节点的实例导致的。

**Comment by jwu** [comment]
问题 1 已经修复, 问题 2 还需要再检查.

**Comment by 2youyouo2** [comment]
2. 是因为粒子从父节点移除后被内部调用unschduleUpdate, 但是他重新添加到父节点后没有被schduleUpdate 导致

**Comment by 2youyouo2** [comment]
我看其他有自己update的Node 基本都有这种情况，如spine这种，是否有onParentChanged这种接口，
可以让子实现这个接口在里面做些事情
