### ISSUE TITLE
Add tmx tilemap wrapper

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#183]
Now we can render tmx tilemap during runtime, next step we need a tilemap wrapper for displaying tilemap in scene editing phase.

**Comment by nantas** [comment]
支持数组那个问题现在解决了没有？那个问题有自己的 issue 吗？

**Comment by 2youyouo2** [comment]
#185，稍后我再修改下tiled map

**Comment by 2youyouo2** [comment]
finished
