### ISSUE TITLE
Add package-studio option to specify a local package path 

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#19]
For package developer, it would be great to load his package directly in package-studio.

Besides packages in `fireball/builtin` and `~/.fireball/packages`, we need a solution to let user specify a path to load local packages from.

The path must have one of the two condition: 

- the path contains a package.json file
- the path contains other folder 

If the package.json in the path folder or sub-folders are not valid or does not exist, those folder or path will be ignored and will not load.

**Comment by jwu** [comment]
Hi @nantas , I've finish this task. However, I can not find a way to run package-studio with parameter in gulp mode. So far this is done in bash through:

```bash
sh utils/package-studio.sh editor-framework/demo/ # load all packages under demo/
sh utils/package-studio.sh editor-framework/demo/grid # load single package
```

I also add some explanation about how package-studio loading packages in our README.md in "Run" section. Feel free to change it if you find a better place.

Document

**Comment by nantas** [comment]
Now gulp command support for package-studio path specification added:
```bash
gulp run-packagestudio --path editor-framework/demo
gulp run-packagestudio --path editor-framework/demo/grid
```

It only works when the electron is run with `child_process.exec`, so you lose all colors in console output 
:(

**Comment by jwu** [comment]
Why not use child_process.spawn instead? It will colorful your terminal. I try to change your script to the one below and found it works well:

```javascript
  var proc = require('child_process').spawn( cmdStr, [
      './',
      '--debug=3030',
      '--dev',
      '--dev-mode=packages',
      '--show-devtools',
      packagePath,
  ], {
      stdio: 'inherit',
  });
```

**Comment by nantas** [comment]
It just doesn't work, with the same command line and options, the last argument with path will not take effect with child_process.spawn. You can check if there's something wrong with the parsing of options in package-studio/init.js.

**Comment by jwu** [comment]
![screen shot 2015-06-06 at 4 41 53 pm](https://cloud.githubusercontent.com/assets/174891/8018998/f950c7ae-0c6a-11e5-842d-301a36f59a69.png)

This is what happen in my machine, I don't see any thing wrong on it.

**Comment by nantas** [comment]
ok, I see what's the culprit,

if one of the options looks like this: `'--dev-mode="packages"'` it will not work,
`'--dev-mode=packages'` works though.

**Comment by jwu** [comment]
Well, it should be --dev-mod=packages, if you agree, I will submit my changes.
