### ISSUE TITLE
Refine the code in scene-view.js for Editor.importPath

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#197]
In the _initEngine there is a code:

```js
        var importUrl = Editor.importPath.replace(/\\/g, '/');
        Fire.AssetLibrary.init(importUrl);
```

When people reading this code, it will have several questions:

1. What is the path format for Fire.AssetLibrary? ( uri, posix path or windows path ?)
2. If Fire.AssetLibrary accept any of them, why Editor.importPath should convert itself into posix style path before sending it?

The reason is come from runtime, and should not let the scene-view worry about it. Because scene-view doesn't known what's the path format the current runtime like. 

I think Fire.AssetLibrary knows the runtime, so move the path formatting code to it will be more reasonable.

**Comment by jareguo** [comment]
我先放到 AssetLibrary 里面统一处理，如果之后有别的 runtime 需要其它路径形式，再考虑新增 API。
