### ISSUE TITLE
很酷的工具，会持续关注，请教几句：

### ISSUE THREAD

**Issue by tcdona** [fireball-x/fireball#2]
希望能有一个egret那样的自动更新程序【我已经被惯坏了吗。。。】

很想知道为啥选用了 atom-shell 而不是 nwjs ?

会有骨骼动画的支持吗，是和spine, dragonbone结合，还是自己做个编辑器？

**Comment by nantas** [comment]
下个版本会有半自动更新（下载完成后用户手动替换）。
骨骼动画会先支持 spine 官方的 runtime，之后再考虑研发自己的支持状态机和混合的骨骼动画工具。

**Comment by jwu** [comment]
我们最开始的时候选用了 nwjs. nwjs 和 atom-shell 本质的区别在于他们对于 io.js event loop 的注入方式. 理论上来说, fireball 的架构更适合 nwjs, 他拥有一个非常好用的 global context, 可以做非常方便的多窗口通信. 但是在实际使用时, 我们发现 nw.js 有以下几个不足之处:

  - 编译 nw.js 非常困难. ( 如果未来考虑自己做 shell 定制, 这将会面临较大的挑战 )
  - bug 多, css 渲染有一些潜在 bug, 报到官方的 issue 中反馈也不及时, 看着官方 900 多个 open issues 感觉有些心寒
  - 项目的迭代速度慢
  - main 入口在 page 层这个设计不太合理

之后我们就改用 atom-shell, 他的 ipc 通信方式确实为开发带来了不小的麻烦, 在一开始设计时需要写很多基础代码来稳定 atom-shell 的多窗口通信. 但 atom-shell 带来的优势也是显而易见的, 他的 issue 反馈及时, 项目轻量所以重新编译简单 (我们已经 fork 了自己的版本 fire-shell). 同时他的新功能迭代也非常的迅速, 在短短一年间已经从 atom-shell 发展成 electron.io, 并被 facebook, slack 等公司用于实际生产, 相信未来会更好.

在这样的情况下, 我们觉得一个稳定强大的基础 shell 才能够让 fireball 做出更多优秀的扩展, 所以最终决定使用 atom-shell (或者 electron) 来开发.

**Comment by tcdona** [comment]
哈哈，感谢这么详细的解答！
