### ISSUE TITLE
More firendly error info about duplicated id in hierarchy tree

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#202]
cocos2d addChild 时，如果忘了 removeFromParent，就会导致 hierarchy 报 `Error: The id already added in the tree: ...` 建议在这里补充点提示信息。
或者，考虑针对 cocos2d 的这个特性调整下 hierarchy item 的索引规则？

**Comment by jwu** [comment]
需要怎么调整索引规则?

**Comment by jareguo** [comment]
使用 path 索引而非 id

**Comment by jwu** [comment]
用 path 索引在上次讨论就被否决了吧, 才会采用了 uuid 来索引的.

**Comment by jareguo** [comment]
或许要考虑将 tree 的 id to item 索引修改成 id to [ item ]，但这又会导致在 hierarchy 中操作 item 时指向不明确的问题，需要发送完整 path 给 engine 才能知道是哪个位置的 item 在进行操作。

我还是想请教下 @pandamicro，为什么 cocos2d 会允许一个 node 被多次 add 到不同 parent 下，如果这是合法的，那么 node.parent 难道不应该返回一个数组吗？不然 removeFromParent 操作该怎么保证正确性？

**Comment by pandamicro** [comment]
应该是不允许的啊，如果一个node首先在parent1下，然后又被add到parent2下，会报错

```
addChild: function (child, localZOrder, tag) {
    ...

    cc.assert(child, cc._LogInfos.Node_addChild_3);
    cc.assert(child._parent === null, "child already added. It can't be added again");

    this._addChildHelper(child, localZOrder, tag, name, setTag);
},
```

**Comment by jareguo** [comment]
谢谢，我知道了，是我们的 debugMode 没有正确启用导致没有报错，麻烦 @2youyouo2 开启 edit mode 下的调试功能吧。

**Comment by jwu** [comment]
@pandamicro 但我一直很好奇, 为什么不做成直接 addNode 就可以帮助转移的 api 形式呢?

**Comment by pandamicro** [comment]
这个算是最早的设计之一，应该是Riq做的，从他的理念来说（他比较笃信Python的信条），感觉应该是API的单一性，addChild不应该做不能被其名字所表达的隐含行为，比如从本来的父节点中移除

**Comment by jwu** [comment]
@jareguo 这个问题最终怎么决定? 由 @2youyouo2 那里开启 edit mode 么?
