### ISSUE TITLE
allow function for `default` keywords

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#205]
To make default keyword can have default value for array and object, we introduce function for them.

```javascript
// array
foobar: {
  default: function () { return [ 10, 20, 30 ]; },
  type: Fire.Float,
}
```

**Comment by jareguo** [comment]
应该是 
```
foobar: {
  default: function () { return [ 10, 20, 30 ]; },
  type: Fire.Float,
}
```
这个方案很早的时候我也建议过，但现在我觉得暂时没必要做。理由是现在的 FireClass 已经太过复杂和庞大了，充满了各种黑科技。关于这个问题的实际使用场景，我认为这只是一个不常用的语法糖，对用户不会有不好的影响，暂时没有做的必要。

**Comment by jareguo** [comment]
关联 issue：https://github.com/fireball-x/core/issues/25

**Comment by jareguo** [comment]
功能已加上去，文档暂时不更了
