### ISSUE TITLE
Support dynamic change property attributes

### ISSUE THREAD

**Issue by 2youyouo2** [fireball-x/fireball#224]
Currently not support dynamic change property attributes like this
```javascript
Fire.attr(wrapper, 'size', {readonly: !value});
```

**Comment by jareguo** [comment]
当前是支持的，只不过我 dump 时没有校验 instance 的 attr

**Comment by jwu** [comment]
这个功能的作用主要是什么?

**Comment by 2youyouo2** [comment]
比如size 这个属性，
我需要动态设置 它是否是readonly 的，
ui那边如果开启九宫格，是需要设置size属性的; 不开启则size 为readonly

**Comment by jwu** [comment]
如果是这样的话, 我觉得 size 属性不是 readonly, 在 inspector 中的表现是 disabled = true

**Comment by jwu** [comment]
@jareguo 我不觉得动态修改 attrs 是一个符合我们引擎设计的 idea. 毕竟 attrs 在早期设计的时候, 是一个代码可视化方案, 书写的时候说他是什么, 他就是什么. 他的动态能力全部都交给 inspector 的 draw 去控制. 所以这个地方, size 在 inspector 中应该是默认为 disabled, 只有当 ui 为九宫格的时候, disabled = false. 和 readonly 没有关系.

**Comment by 2youyouo2** [comment]
那这样 就需要提供一个额外的属性来控制 size 是否 被 disabled了吧

**Comment by jareguo** [comment]
OK，有更好的做法也行。之前是因为在 0.4 没有别的选择，所以当时就做了 attr 动态重载的策略，不但是设置 disable，也用来更新 enum，更新 visible 等。

**Comment by jwu** [comment]
开启九宫格这个属性不就是了么? 在 inspector 中可以这么写:

```html
<editor-prop prop="{{target.size}}" disabled="{{!target.slicedSprite.value}}">
```
