### ISSUE TITLE
Failed to send same array via ipc

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#227]
Electron 的 ipc 参数如果包含了对同一个 array 的多处引用，多出来的引用就会变成 null。这应该是 Electron 为了解决数据的循环引用而加进去的保护措施。需要进一步确认。

**Comment by jareguo** [comment]
经过测试，这是 Electron 的 feature，好棒喔！
参考：https://github.com/atom/electron/issues/1229

**Comment by jwu** [comment]
那我们解决方案是?

**Comment by jwu** [comment]
估计我们需要 json.serialize 成 text 进行传输了是吧?

**Comment by jareguo** [comment]
建议遇到的时候再针对性的进行一次 deep copy。就像我前面提交的代码那样。
