### ISSUE TITLE
`npm run test` should support folders like: sub-app or sub-app/test

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#23]
Currently, I can run test through:

```bash
npm run test dashboard/test/index.js
# or 
npm run test dashboard/test/foobar.js
```

I wish I can run test by folder, such as

```bash
npm run test dashboard/
# or
npm run test dashboard/test/
```

 - if user run `npm run test {sub-app-name}/` it will search if a `test/` folder in it, and then go to the non-single-file test phase ( the else part in run-test.js ).
 - if user run `npm run test {sub-app-name}/test` it will go directly to non-single-test test phase.

**Comment by nantas** [comment]
folder wide test input is now supported:
```bash
npm run test -- dashboard
# or
npm run test -- dashboard/test
# or
npm run test -- dashboard/test/index.js
```
will all load `dashboard/test/index.js` and go through the test cases in that file.

Run test will fail if you provide a path without a valid `index.js` file or can't find `path/test/index.js` file.
