### ISSUE TITLE
Check the frame rate when engine paused

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#244]

**Comment by jareguo** [comment]
@2youyouo2 我看了一下，现在 pauseRuntime 后，cocos 确实是暂停的，但是 cocos 没有暂停后就停止渲染这个概念。如果要加的话好做吗？

**Comment by jareguo** [comment]
还有 stopRuntime 这个 api，之前因为 reload webview 就行了一直没做，现在加的话容易实现吗？
cc @jwu

**Comment by jwu** [comment]
现在为什么还需要 stopRuntime ?

**Comment by 2youyouo2** [comment]
他是下一帧停止，你要当前帧就停止？
他渲染到一半的时候是没办法停止的。

**Comment by jareguo** [comment]
> 现在为什么还需要 stopRuntime ?
stopRuntime 可以不要，我是担心以后会增加一个 stop 按钮

**Comment by jareguo** [comment]
> 他是下一帧停止，你要当前帧就停止？
他渲染到一半的时候是没办法停止的。

下一帧停就可以了

**Comment by jareguo** [comment]
方法比较 hack，还是暂时不改吧
