### ISSUE TITLE
Should not playing particle or other things in editor?

### ISSUE THREAD

**Issue by 2youyouo2** [fireball-x/fireball#249]
@jwu 建议不再在编辑器编辑状态下播放粒子或其他可以动态变化的对象，编辑器只做静态编辑。

但是后面添加了动画的功能的话，编辑器就不再只是静态编辑了，也会包含动画的预览。

那么粒子或其他可以动态变化的对象是否还需要停止呢？

@jareguo @nantas

**Comment by jwu** [comment]
动画的预览是由 timeline 时间轴去驱动的, 是一种帧驱动的方式, 从工作原理上看, 他还是属于静态编辑的范畴.

**Comment by jareguo** [comment]
我认为还是要等粒子的 preview 功能和动画的 preview 功能做完再移除现有的设计。毕竟现有的功能工作良好，设计合理，对用户而言还是利大于弊。

**Comment by jwu** [comment]
我目前在放置 particle 的时候, 会有非常大的卡顿, 影响了场景中放置 particle 的操作体验. 并且我在设置 particle 参数的时候, 也会遇到非常大的卡顿. 我觉得禁止 particle 的播放在整个操作体验上会更加优秀.

**Comment by jareguo** [comment]
我重新在 retina 上测试了下 SmallSun 这个粒子，帧率确实很低(目测不到 5 帧)，如果用回普通显示器的话，就很流畅。帧率低的原因主要是粒子数量太多了，如果像 0.4 的默认效果那样降低到 10 个左右，就不会卡了。也就是说只有在 retina 下编辑非常庞大的粒子才会遇到 `非常大的卡顿`，我不反对现在剔除粒子自动播放功能，但也不是很希望为了特殊情况下的卡顿就影响实际项目的开发需要。最好是加一个播放粒子的按钮。

建议 @2youyouo2 参考一下 0.4 版本的默认的粒子设置，那个效果会更接近于手机项目的实际使用情况，通屏粒子数也就差不多10个，已经能满足正常的编辑需求。(我们现在手工创建的粒子，根本看不到效果，要调的属性太多了)

**Comment by jwu** [comment]
先关闭吧, 等到多数用户反馈希望在编辑器中预览粒子了我们再想办法. 如果你一开始就加入了这么高大上的需求, 后期技术上难以支持其在编辑器中预览要砍掉这样的减法操作更加伤害用户的感情. 与其如此不如一开始就培养用户在 target device 上看效果的习惯.

**Comment by jareguo** [comment]
抱歉，我接上电源后发现就没那么卡了，所以我觉得暂时没有砍掉的必要了。建议等 retina 用户投诉不接电源时无法编辑上百个的粒子时再考虑给予关闭选项。反正现在用户量也不是很多，能有什么历史包袱？
做产品就是一个不断权衡利弊的过程，不要试着满足所有人。

**Comment by jwu** [comment]
我想知道 disable 这个功能的难度有多大? 会花费很长时间么?

**Comment by 2youyouo2** [comment]
disable 的话很快

**Comment by jwu** [comment]
好, 那先关闭这个功能, 我应该不用再说第三遍了吧.

**Comment by nantas** [comment]
你还没有办法直接在 browser 预览粒子的情况下，现在关闭粒子播放那用户就彻底用不了调整粒子参数的功能了，建议默认 preview 选项关闭，用户可以手动打开

**Comment by jareguo** [comment]
那现在要做一个 preview 选项？（就像我上面发的图片那样）

**Comment by 2youyouo2** [comment]
所以结论是默认加个preview选项，用户开启preview后 可预览粒子?
这个preview选项是加在wrapper上？

**Comment by nantas** [comment]
做个 preview 开关，默认关闭，打开后可以在场景中看到粒子播放的渲染
