### ISSUE TITLE
Can not refresh inspector after value created

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#250]
点击 Create 按钮后，Inspector 不会刷新，要重新选中当前物体才能看到新创建好的值。
![image](https://cloud.githubusercontent.com/assets/1503156/9438739/392a44fc-4a93-11e5-96de-50b76bc7c374.png)

**Comment by jwu** [comment]
Fire.Vec2 是值类型, 理论上不应该传递 null.

**Comment by jareguo** [comment]
用户有可能在脚本里设为 null，这个没法阻止吧
