### ISSUE TITLE
scripts importing error message is garbled

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#252]
如果脚本有语法错误，移动脚本时会出现下面这样奇怪的报错：
```
Failed to move asset from assets://NewScript.js to assets://NewScript11.js, messages: SyntaxError: unknown: Unexpected token (10:4)
[0m   8 |             [90m// type: Fire.String[39m
   9 |         [32m}[39m[1m,[22m[35m1[39m
> 10 |     [32m}[39m
     |     ^
  11 | [32m}[39m[34m[1m)[22m[39m[1m;[22m
  12 | 
  13 | module[1m.[22mexports [1m=[22m Fire[1m.[22mClass[34m[1m([22m[39m[32m{[39m[0m
```

**Comment by jwu** [comment]
@2youyouo2 please find out the problem in builtin/fire-assets/meta/javascript.js. I guess this is message format problem in Babel.

**Comment by 2youyouo2** [comment]
原因是 babel  默认开启了 highlightCode 选项，这会在error 信息里插入一些ANSI highlight syntax code, 而console panel识别不了这些code.
![image](https://cloud.githubusercontent.com/assets/1862402/9571702/7f92054c-4fd4-11e5-9281-d43526c72310.png)

shell打印出来的code:
![image](https://cloud.githubusercontent.com/assets/1862402/9571746/63357b26-4fd5-11e5-9dfc-e333e9774f7c.png)



disable highlightCode 后可去掉附加的信息：
![image](https://cloud.githubusercontent.com/assets/1862402/9571721/daa0f222-4fd4-11e5-979c-16a3f28e9506.png)

所以目前先disable highlightCode？

**Comment by jwu** [comment]
好的, 先 disable, 等到未来 console 支持 markdown 和 html highlight  后再考虑支持这个 feature
