### ISSUE TITLE
Fireball官网API请求部分的设计.

### ISSUE THREAD

**Issue by w88975** [fireball-x/fireball#254]
由于官网重构后,没有采用Meteor去做前端部分的渲染(考虑到搜索引擎的优化),所以一些涉及到用户部分的操作就需要在后端进行处理,而不是直接暴露给客户端.

问题出在这里,之前的官网,涉及到用户部分的操作,都是通过accounts服务器的API来请求的,这些操作都是在客户端完成,但重构后,由于页面在后端渲染,这些部分操作,会移到后端去做,由客户端转移到了服务器端.

例如一个简单的例子: 用户信息修改的页面.

- 在渲染页面之前,需要判断用户的合法性,如果用户没有进行登录,那么返回的不是用户信息页面,而是提示未登录的页面
合法性验证不只是验证cookie里是否含有token的字段,还需要去验证token是否过期等等.  这里需要用到accounts服务器的API来验证.  但是在官网服务器,每次一个用户访问当前页面,官网服务器都需要对accounts服务器进行一次HTTP请求

     由于是分为两个服务器,请求之前的延迟都会叠加到用户请求的时间,就会导致用户请求一个页面的时间大幅度增长,而如果是官网服务器直接对数据库进行查询,就可以省去官网服务器对accouts服务器的延迟.
     再加上accouts服务器采用的是https链接,又能省去验证SSL证书,dns解析的时间,dns解析失败等(虽然可以忽略不计).

- 我和@yorkie 讨论了一下,觉得可以把accouts这部分封装成一个lib,方便官网服务器去做一些数据库的操作,这样就能大幅度的优化查询速度.

- @nantas 觉得 如果把accouts封装成lib,给官网服务器用,会涉及到安全性问题,数据库不应该直接暴露给官网服务器.

不知道大家看法是怎么样的

**Comment by w88975** [comment]
accounts 抽象出来的API,有以下需要的部分.

- 1. token验证 [userId,token] -- 验证token合法性,是否过期
- 2. 用户信息获取 [userId,token] -- 获取用户的资料 <用户名,邮箱,头像等非敏感信息>
- 3. 博客部分 
       - 1.获取所有博客 [category] -- category 参数为博客分类,不传默认返回所有分类 (考虑做不做分页)
       - 2.获取所有博客分类 
       - 3.获取单篇博客详细内容 [博客ID或者Name]
- 4. downloads列表
       - 1. 获取所有downloads列表 
       - 2. 获取某个版本的changelog, 下载地址等 [version]

**Comment by w88975** [comment]
剩下的就是一些用户的注册,登录,信息修改等等 这部分可以直接走accouts服务器API

**Comment by yorkie** [comment]
我检查了一下，现在的developer-accounts就已经是模组了，使用方法是：

1. 加入dependencies，使用如下url：`git+https://git@github.com/fireball-x/developer-accounts`，因为这个仓库是私有仓库，所以在安装的时候可能需要加入token。或者是使用submodule下载源码～。

2. 获取`app`

```js
var app = require('developer-server');
app.models.FireAccessToken  // token
app.models.FireUser // user
```

a. 验证token合法性，可参见：https://apidocs.strongloop.com/loopback/#accesstoken-prototype-validate
b. 获取用户的资料，可参见：https://apidocs.strongloop.com/loopback/#persistedmodel-findone

另外，现在accounts这边并没有提供博客或者下载的API，是新的需求么？@w88975 @nantas

**Comment by yorkie** [comment]
另外，这里issue是否应该移到 https://github.com/fireball-x/developer-accounts 进行，因为这个是公有的仓库。

**Comment by w88975** [comment]
@yorkie  博客和下载的，在数据库里有blog和download两个conllection
这两个也需要直接进数据库查询，所以能封装一下最好

**Comment by yorkie** [comment]
但是那个是之前的系统的，在accounts里面并没有这两部分，而且那样结构会比较乱～

**Comment by yorkie** [comment]
那两个应该是原来meteor加进去的，所以我这边也是无法直接提供的，具体还需要做数据库迁移～ 这里可能需要 @nantas 的意见

**Comment by nantas** [comment]
讨论移到 developer account 那边，这里关闭。
