### ISSUE TITLE
Node type defined by wrapper is wrong in inspector

### ISSUE THREAD

**Issue by 2youyouo2** [fireball-x/fireball#261]
按下面的方式在wrapper中定义的node type 在inspector中的显示是不正确的
```javascript
mask: {
    default: null,
    type: PIXI.DisplayObject
}
```
![image](https://cloud.githubusercontent.com/assets/1862402/9649926/546e178c-522e-11e5-8863-a2b4530b1386.png)

**Comment by jwu** [comment]
@jareguo 我查了一下, 如果实在 wrapper 中, dump 出来的 type 是 null
