### ISSUE TITLE
Why are passwords limited to 25 characters?

### ISSUE THREAD

**Issue by krainboltgreene** [fireball-x/fireball#27]
It's kinda annoying and seems arbitrary.

**Comment by nantas** [comment]
You're right, this is an unnecessary check which should be removed from login/register panel.
We will make sure it's not there in refactored 0.5 version.

**Comment by jwu** [comment]
I've add this as a sub-task in #26, so this issue will be closed.

**Comment by krainboltgreene** [comment]
Thanks!

On Wed, Jun 10, 2015 at 11:10 PM, Wu Jie <notifications@github.com> wrote:

> Closed #27 <https://github.com/fireball-x/fireball/issues/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fireball-x/fireball/issues/27#event-328115459>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115
