### ISSUE TITLE
New app install has empty HELP pane

### ISSUE THREAD

**Issue by krainboltgreene** [fireball-x/fireball#28]
![screen shot 2015-06-10 at 10 43 04 pm](https://cloud.githubusercontent.com/assets/334809/8099417/49b73034-0fc2-11e5-9a33-60c20cd0b19c.png)

Mac (latest)
Fireball (latest)

**Comment by nantas** [comment]
Sorry for the empty pane. That part will be finished in 0.5.

**Comment by jwu** [comment]
Hey @nantas , what should I do for the help page in Dashboard? Should I redirect it to the document site?

**Comment by nantas** [comment]
plz create a placeholder html page, I'll populate the content

**Comment by jwu** [comment]
added :)

**Comment by nantas** [comment]
new help page delivered at 102168fa21

![image](https://cloud.githubusercontent.com/assets/344547/8404587/bca377b6-1e80-11e5-99e2-d077b26c4aa1.png)
