### ISSUE TITLE
coding style guideline

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#30]
@nantas please create a document to help new comers and contributor write script we like.
@jareguo please add anything you wish for engine's coding style in Engine section.

## General

 - use dash naming rules for files and folders ( e.g. `foo-bar` )
 - use camelCase naming rules for module methods and properties ( e.g. `fooBar` )
 - use CamelCase naming rules for modules ( e.g. `FooBar` )
 - use upper-case for the first character of required module ( e.g. `var Foo = require('foo')` )
 - use `_` prefix for private method or variables ( e.g. `var _foobar = 'FooBar'` )

## Editor, Plugins and Editor-Framework
 - Recommend Ipc message in the form of `module-name:ipc-channel-name` ( e.g. `foo-bar:say-hello`)
 - Recommend DOM event in Polymer in the form of `_onMyEvent` ( e.g. `<foobar on-click="_onClick" />`)

**Comment by jareguo** [comment]
I have wrote a guildline at NewComer: https://github.com/fireball-x/newcomer/blob/master/Basic/javascript-codestyle.md
Renew it if you want.
