### ISSUE TITLE
Can we inspect FireClass in Inspector directly

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#33]
@jwu Instead of creating html pages for each node/asset, how about providing a most common solution which just inspect FireClass directly?

**Comment by jwu** [comment]
Sure we have, the register method in inspector looks like this: 

```
inspector.register ( Fire.NodeWrapper, node-inspector.html );
inspector.register ( Fire.Entity, entity-inspector.html );
inspector.register ( Fire.SpriteNode, sprite-node-inspector.html );
...
```

**Comment by jareguo** [comment]
"Sure we have" means we may indeed inspect `Fire.SpriteNode` WITHOUT register the `sprite-node-inspector.html` ?

**Comment by jwu** [comment]
According to my example code above, if you have special layout for Fire.SpriteNode, you have to manually register `sprite-node-inspector.html`, otherwise, it will gose to the default inspector which is `node-inspector.html` if Fire.SpriteNode is inherits from Fire.NodeWrapper.
