### ISSUE TITLE
better mocha report for full test

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#34]
The current mocha report is designed for single file test, but it doesn't fit the demand when we running full test. So we need a better mocha report.

My advice is, keep the Spec mocha report which is good for single task testing. And make a new one for full report based on dot report or [matrix reporter](https://github.com/tj/mocha-matrix). More reporters can be found here https://github.com/mochajs/mocha/wiki#interfaces--reporters

## How dose the test running in current code?

1. We trigger the utils/run-tests.js
1. run-tests will SpawnSync for each tests by loading each module's test/index.js
  1. each test will use {electron.app} --test {my/test/file} to run it
  1. in editor-framework/init.js it take care about the --test argumen, and require the `./core/test-runner` and call `Test.run( 'my/test/file' )` to run it
  1. the Test.run will add the test file to the mocha instance, and invoke mocha.run() so that the test will be run in the `core-level`
  1. **If you going to run your test in page-level**, you have one more step that in your `core-level` test, open a window, and let it load your `page-level` test environment, which needs you load `editor-framework/test/page-utils/page-runner.html`
    1. It will load the `editor-framework/page/test-runner.js` and mocha, chai with it for page test
    1. run your test code afterward. There is a example to show how this works ( `editor-framework/test/behaviors.html` and `editor-frameworks/test/behaviors.js` )

## Where can I improve the code?

First, since we need all reports collect in one place, we should make sure our utils/run-tests.js will get the results from each spawnSync.

Second, editor-framework's Test.run should detect if this is a test-all case, and change mocha's report from Spec to a one that can communicate with spawnSync

Third, page-level tests should first report back to core-level (this also benefited for single test report), and then communicate with spawnSync.

This task should use pull-request and I will review the code.

**Comment by nantas** [comment]
- [ ] Combine multiple `Test.run` into a single call with a list of test files 
- [ ] When running test with multiple files, only output full spec when there're failures
- [ ] Collect page-level test output

**Comment by nantas** [comment]
Most of mocha's HTML format reporter output only works in browser testing, and the builtin `doc` reporter has too many redundant information. So currently the best option is to have an alternate "silent" report for running full test, collecting failed test and send them back to run-tests process via IPC message, then re-run those failed tests with normal `Spec` reporter.

See PR #38 for details.

**Comment by nantas** [comment]
added page-level test counting display.
