### ISSUE TITLE
考虑引入 Asset 定义

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#35]
亲爱的 @jwu @2youyouo2 @nantas 
对于 runtime 及 js game engine 来说，往往没有 Asset 的概念（有的往往是 ResMgr）。但是对于 engine-framework 和 editor 来说，没有 Asset 却有诸多不便。
但是如果不做简化，直接引入 Asset 后就容易牵扯出之前 Fireball 的那一整套复杂的东西，包括 Meta, Import/Export, hot reload asset, cache and unload asset...
所以本 issue 讨论下如何简化 Asset，并且简化后的 Asset 能用来干什么。

如何简化：
- Asset 仍然包含 `_uuid`, 还要提供 `asset.url` 这个 getter。
- Fireball 只提供非常基本的几个 asset，例如texture, 九宫格
- runtime 的 Asset **不要求**包含真实数据，最终资源通过 `asset.url` 自行加载，url 对 runtime 是最直接的
- Asset 保留 rawData 的概念，但是不对 rawData 做任何处理，只负责保存 rawData 的后缀名。

简化后能干什么：
- runtime 可以继承 Fireball 提供的 Asset，也可以注册自己的 Asset:  
  `Fire.AssetDB.register( '.txt', cc.SpriteFrame);`
- Asset 需要提供 checker method，来验证指定的 raw data 是不是所属类型。  
    `Runtime.SpriteFrame.validateAsset(callback);`
    - 当验证通过后，editor 可以调用 Asset 的 createNode 方法，由 asset 负责创建场景对象    
    `Runtime.SpriteFrame.createNode(callback);`
- 序列化场景时，有一个全局统一的 uuid 处理方式。
- Inspector 上能够用来链接指定类型的资源。  
```js
Runtime.SpriteWrapper = Fire.Class({
    ...
    properties: {
        sprite: {
             get: ... ,
             set: ... ,
             type: Runtime.SpriteFrame
        }
        ...    
    }
});
```
- (备选) 当 raw data 改变时，asset-changed 的 ipc 不再全局统一处理，而是由 runtime 自行注册 `this.sprite.on('changed')`，并实现重新加载机制。

**Comment by jwu** [comment]
在基类的 Fire.Asset 里, 请定义这样两个函数:

```javascript
Fire.Asset = Fire.Class({
  serialize: function () {
    Editor.serialize(this);
  },
  deserialize: function ( jsonObj ) {
    Editor.deserialize( this, jsonObj );
  },
});
```

**Comment by jareguo** [comment]
@jwu 已提交
