### ISSUE TITLE
initialize the canvas studio

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#36]
- [x] check the project path
 - [x] init asset-db
 - [x] init engine-framework
 - [x] open the main-window

**Comment by jareguo** [comment]
还是和以前一样，你只需要调用 Fire.AssetLibrary.init()，还有 Fire.Engine.init()

**Comment by jwu** [comment]
for both core and page level ?

**Comment by jareguo** [comment]
core level 只要把脚本 load 进来，不需要调用初始化方法。

**Comment by 2youyouo2** [comment]
page 需要你加载一个html(用来加载cocos-html5)，有什么写法上的要求以及目录的要求？

**Comment by jareguo** [comment]
core:
```
Editor.require('app://engine-framework/src'); 
```
page:
```
Editor.require('app://engine-framework/src'); 
Fire.AssetLibrary.init("%library path%");
Fire.Engine.init({
    width: width,
    height: height,
    canvas: canvas
}, callback);
```

**Comment by 2youyouo2** [comment]
<script>
            document.ccConfig = {
                "renderMode"    : 2                 // 0: auto, 1:Canvas, 2:Webgl
            };
        </script>

        
        <script type="text/javascript" src="app://runtime/runtime-cocos2d-js/lib/cocos2d-html5.js"></script>

        <script>
            // engine framework
            Editor.require('app://engine-framework/src/index');

            // cocos
            Editor.require('app://runtime/runtime-cocos2d-js/src/index');

            var option = {
                width:  400,
                height: 400,
                canvas: 'gameCanvas'
            };

            Fire.Engine.initRuntime(option, function () {
            });

        </script>

**Comment by jwu** [comment]
对于 runtime page 层初始化, 我希望通过这样的方式 runtime-cocos2d-js/index.html:

```html
<script>
    document.ccConfig = {
        "renderMode" : 2 // 0: auto, 1:Canvas, 2:Webgl
    };
</script>

<!-- cocos html5 -->
<script type="text/javascript" src="./lib/cocos2d-html5.js"></script>

<script>
    // engine framework
    Editor.require('app://engine-framework/src');

    // cocos
    Editor.require('app://runtime/runtime-cocos2d-js');
</script>
```

**Comment by jareguo** [comment]
整理一下 canvas studio 的加载方法：
```html
<script>
    document.ccConfig = {
        "renderMode" : 2 // 0: auto, 1:Canvas, 2:Webgl
    };
</script>
<script type="text/javascript" src="./lib/cocos2d-html5.js"></script>
<script>
    Editor.require('app://engine-framework');
    Editor.require('app://runtime/runtime-cocos2d-js');
    // ....
    Fire.AssetLibrary.init("%library path%");
    Fire.Engine.init({
        width: width,
        height: height,
        canvas: canvas
    }, callback);
</script>
```
