### ISSUE TITLE
implement scene-view store and restore

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#45]
播放步骤如下：
- scene 响应 `scene:play` 事件，开始转菊花
- scene 发送 `play` 给 webview
- webview 保存当前场景(JSON)，将场景发回给 scene
- scene 保存 selection 等
- webview 进入 game mode:
    - 清空 gizmo (可选)
    - 复位场景摄像机
- webview 开始播放
- scene 停止转菊花

```
其中 webview 暂存的场景将包含 scene camera 信息
```

回退步骤如下：
- scene 响应 `scene:stop` 事件，开始转菊花
- scene 直接 reload webview
- webview 初始化(Fire.Engine.init)
- webview 向 scene 请求加载的场景
- scene 发送之前暂存的场景给 webview
- webview 读取场景
- scene 还原 selection
- scene 停止转菊花

**Comment by jwu** [comment]
我整理一下播放步骤的简单代码

```javascript
Ipc.on( 'scene:play', function () {
  Fire.Engine.dumpScene( function ( err, jsonObj ) {
    Editor.stashScene( jsonObj ); // including scene-json, current-selection, editor-camera...
    Fire.Engine.play(); // ?? should I recieve callback here ???
    Ipc.sendToHost( 'scene:played' );
  });
});
```

**Comment by jwu** [comment]
stop 时, Engine 需要有事件让用户注册一些 sync 操作.

**Comment by jwu** [comment]
我仔细想了一下, stop 不需要发送 ipc scene:stop 事件. 当 stop 时, webview.reload() 被调用, 进入 webview 初始化装填. 初始化代码如下:

```javascript
 Async.waterfall([
    function (next) {
      Fire.Engine.restoreScene(next);
    },
    function ( next ) {
      Ipc.sendToHost( 'scene:ready' );
      next ();
    },
  ], function ( err ) {
    // anything wrong, goes here.
  });
```

**Comment by jareguo** [comment]
stop 时， webview 只要执行：
```js
function beforeClose () {
    if (Fire.Engine.isPlaying) {
        Fire.Engine.stop();
    }
}
```
用户代码就会被触发
```js
Fire.Engine.on('stop', function () {
    console.log("bla bla bla");
}));
```
