### ISSUE TITLE
How to use markdown link in parameter?

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#46]
We use in this way:
```
/**
 * @class Menu
 * @constructor
 * ... ...
 * @param {object} [webContents] - A [WebContents](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#class-webcontents) object.
 */
```
But the doc looks like:
![image](https://cloud.githubusercontent.com/assets/1503156/8326607/c57f23de-1a94-11e5-9c56-967a2cf72d04.png)

(See `webContents`)

**Comment by nantas** [comment]
this bug should be reported in Firedoc repo
