### ISSUE TITLE
Is fire-shell deprecated?

### ISSUE THREAD

**Issue by qt911025** [fireball-x/fireball#48]
The task `gulp bootstrap` is not equivalent to the commands below (in chapter "Install" of README.md).
There is no fire-shell at version 0.27.3. It seems that the origin electron is used by default.

**Comment by jwu** [comment]
So far, we are developing based on Electron, fire-shell always following up before we publish a version. Right now we are active developing the 0.5 and have no time to build a fire-shell for testing.

**Comment by qt911025** [comment]
Thx.
