### ISSUE TITLE
to much pain without CoffeeScript, would it be supported?

### ISSUE THREAD

**Issue by 5alamander** [fireball-x/fireball#51]
rt

**Comment by 5alamander** [comment]
And the default size of the code editor does not fit my screen.

How can I use a custom editor, such as Sublime , Webstorm, or Atom.
I mean that it will navigate to the Editor when I click the Script.

**Comment by jwu** [comment]
We are considering support CoffeeScript and TypeScript in 0.5. Also we allow user custom its text editor in 0.5.

**Comment by jwu** [comment]
I'm working on the function to allow window smart fit the screen size if the original doesn't. So this will benefit the code-editor when it is done.
