### ISSUE TITLE
import asset with related asset

### ISSUE THREAD

**Issue by 2youyouo2** [fireball-x/fireball#58]
假设 有粒子文件 1.plist, 而1.plist 使用到了2.png图片
import 1.plist 和 2.png 的时候会将 文件拷贝到library/imports 下并修改文件名为id
333333.plist  和 444444.png

那么在解析333333.plist 的时候依然会试图读取 2.png，但是在当前目录下是找不到2.png了的。

与 @jareguo 讨论的方案是 import 1.plist的时候同时拷贝2.png到 library/imports 333333.plist的目录下并保留原名，设置333333 asset 的rawFiles 为[333333/333333.plist, 333333/2.png]

**Comment by jareguo** [comment]
我认可这种做法。我建议所有 rawFile 统一放到以 uuid 命名的目录下。asset 的 rawFiles 数组里面存相对这个目录的路径。
这样就会导入成为：
imports/33/333333 和 imports/33/333333/1.plist 和 imports/33/333333/2.png

但这里有个矛盾的地方时 asset 文件本身和目录重名了，所以我们是否应该要把 333333 重命名为 333333.json？

**Comment by jwu** [comment]
Confirmed, I will add a task in asset-db for this.
