### ISSUE TITLE
implement node.setPath

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#63]
Please add `node.setPath` function in engine-framework or runtime. The node.setPath will accept a `path` and a `value` as parameters, it will evaluate the `path` and setup the `value` properly.

Examples:

```javascript
node.setPath( 'foo.bar', 'Hello World');
node.setPath( 'position.x', 10);
```

**Note:** When setPath set to a value-type's sub properties, such as `pos.x`, `color.r`, or set to a get-set-type's sub properties, it will clone a new value and set the entire property instead.

**Comment by jareguo** [comment]
setPath 换个名字吧，感觉跟 io 有关联似的，叫做 setValueByPath 如何？
而且我不建议在 runtime 层和 wrapper 层上增加太多功能，实际上这是一个 node 和 wrapper 无关的 utility method，把 namespace 放到 Editor 上吧？

**Comment by jwu** [comment]
ok, 他属于 engine-framework 的 editor 扩展部分么?
setValueByPath 叫做 setPropertyByPath 如何呢? 毕竟他是可以操作 get/set 的

**Comment by jareguo** [comment]
对。OK。
