### ISSUE TITLE
Failed to move entities in hierarchy 

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#69]
I've found several issue when moving entity in hierarchy:

1. move lots of nodes into one node
1. failed to change the sibling node (move under same parent)

I also found useful document for tree diff solution: https://github.com/benjamine/jsondiffpatch/blob/master/docs/plugins.md, may be you can try this to get a robust diff method.

**Comment by jareguo** [comment]
Can not use jsondiffpatch because it will not sort the order of deltas. It will has the same problem with the bug of this issue.

**Comment by jareguo** [comment]
重新调整了 diff 的策略，现在没问题了，麻烦再多测看看
