### ISSUE TITLE
Add building pipeline

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#70]
as title

**Comment by jareguo** [comment]
已加上，现在导出前要先选中要发布的场景

**Comment by jareguo** [comment]
@nantas 麻烦帮忙配置一下预览服务器相关内容，之前你的代码我放在 fireball/canvas-studio/core/gulp-build.js
@jwu 麻烦监听 `'builder:state-changed'` 事件，第一个参数是 state，第二个参数是 progress，第三个参数是错误信息

**Comment by nantas** [comment]
预览服务器加上了，会在 canvas-studio 的 init.js 里执行启动，我这里现在无法看到要 build 的场景列表。

**Comment by jareguo** [comment]
场景列表功能要等以后再加
