### ISSUE TITLE
dump node can send class chain so that ui-properties can evaluate it

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#78]
Right now, all types that wants to present in inspector needs to register themselves in ui-property. This is insane, people will be tired of register them one by one. 

To solve the problem, dump node must also send class chain information, after that, in the inspector, when I evaluate a type to control, I will lookup its class-chain table, and try to find a registered type on it from parent to parent.

**Comment by jareguo** [comment]
added `extends` array in type table，just like:
```
      types: {
          Sprite: {
              extends: ["Node", "FObject"]
              properties: {
                  key1: {
                      default: 0,
                      type: 'Integer'
                  }
              }
          }
      }
```
