### ISSUE TITLE
try to reproduce the Electron bug in a pure environment.

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#79]
Currently there have a bug in fireball that will make the HTML imports have deadlock (pending) in webview sendSync ipc method.

It happens like this:

1. a ipc message keep sending from hierarchy to scene to `query-hierarchy`
1. the scene will use webview.send() to transfer the `query-hierarchy` message
1. the `webview.send` actually have a ipc sendSync method called in it ( GetGuestWebContents() )
1. when a select an item in inspector, the inspector will invoke HTMLImport, which will add link and onload method on it

The problem is onload will be blocking and gets deadlock when in the mean time there's a webview.send processing. 

We need to simulate this problem to make it 100% happens so that we can send a issue to Electron to help them locate the problem.

**Comment by jareguo** [comment]
Can not reproduce this bug in a pure environment, just pushed codes to https://github.com/jareguo/reproduce-electron-ipcsync-bug.
