### ISSUE TITLE
Comments translation in tutorial and examples

### ISSUE THREAD

**Issue by kefirchik** [fireball-x/fireball#8]
Hi! It's very cool project! Thanks.
It will be very nice if comment lines in examples projects would be translated to english.
I can do it only with google translate, if it's ok I'll make a PR :smile:

**Comment by nantas** [comment]
We just updated English version of our first tutorial: http://docs.fireball-x.com/tutorial/duang-sheep/step1/

In the markdown we translated all the code example comments to English. The source code will be updated later.

Also, if you find the tutorial not clear or has mistakes, a PR is very welcome!

- Tutorial Repo: https://github.com/fireball-x/tutorial
- Documentation Repo: https://github.com/fireball-x/docs-en

Cheers!

Nan

**Comment by kefirchik** [comment]
Thanks a lot! 

I close this issue for now
