### ISSUE TITLE
Allow control framerate, request repaint in scene-view

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#80]
In editor-level, developers usually wish they can control the frame-rate, also wish to manually repaint. We choose late draw for our scene view for performance, so here is some of the interface I wish engine-framework and runtime can implemented:

1. Fire.engine.setFramerate( fps );
1. Fire.engine.repaint();

The repaint will not be triggered immediately, it will debounce in current frame to make sure only one repaint called each frame.

When repaint and framerate-update working together, the framerate-update will check if this frame has a repaint called and stop calling itself during the frame. 

Note: make sure repaint called after logic update.

@jareguo

**Comment by jareguo** [comment]
实际上这等于允许了 [暂停-编辑] runtime。要实现这种级别的逻辑控制有点复杂，可以参考 0.4 版本的 cocos 的 rendercontext 和 runtime。我建议将接口预留下来，功能都等到 0.5 以后再做。

**Comment by jwu** [comment]
好的, 如果实现情况复杂, 我们就放到 0.5 以后进行.
