### ISSUE TITLE
Rename api with "runtime" suffix to "N"

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#84]
上次将 runtime 替代 node 后，很多 api 变得很长，我都快看哭了。
经过讨论，这里还是决定改回去，不过为了让 editor 开发者更容易区分，将 Node 改成大写 N 结尾这种很特殊的写法。
所以 runtimeTarget 改成 targetN，runtimeParent -> parentN

另外 Fire.node 的用法和上面的改动不一致，请将 Fire.node(node) 改成直接 Fire(node)。

我补充下个人看法，不是所有 api 都一定要区分 Wrapper 和 Node 的，只有那些 public 并且返回值或者输入参数跟节点有关的，才需要做这个区分。这也就是 createRuntimeNode 其实还是叫 createNode 就行，不一定非要改成 createNodeN 的原因，毕竟 createNode 本身没有输入参数也没有返回值，也不存在对应的 createWrapper，没有误用的可能性。

**Comment by jareguo** [comment]
我还有一个建议是，把 Fire 声明成一个 function，调用 Fire(node) 就相当于 Fire.wrapper(node)。

**Comment by jwu** [comment]
好想法. 我赞同.
