### ISSUE TITLE
Better network support in China

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#86]
User in China complain at me about network problem especially when downloading Electron from s3.Amazon server. Any idea how can we solve this problem for both fireball and editor-framework?

**Comment by nantas** [comment]
Now use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) instead of gulp-download-fire-shell.

This way we can download electron from npm.taobao.org.

The task is still the same:
```bash
gulp update-electron
```
