### ISSUE TITLE
Support add button in hierarchy panel

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#88]
Please take _onMenuPopup in  `editor-framework/page/ui/panel/tab.js` as example, and implement the add button in hierarchy panel.

The add button should support:

 - create sprite
 - create particle
 - create text
 - ...

**NOTE:** if we select a node, it will create node besides it.

**Comment by jareguo** [comment]
现在 editor-framework 有菜单相关接口吗？菜单需要反注册吗？

**Comment by jwu** [comment]
先 hardcode, 菜单注册相关的放到接下去的 milestone 调整

**Comment by jareguo** [comment]
改好了，你看看

**Comment by jareguo** [comment]
改好了，你看看

**Comment by jwu** [comment]
well done!
