### ISSUE TITLE
The basic flow for asset edit, compile and scene reload

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#90]
@jareguo , would you mind to write a basic flow and the key functions when we edit scripts and trigger the compile process.

1. When script deleted what should I do
1. When script edited what should I do
1. When script created what should I do
1. When script renamed what should I do

**Comment by jareguo** [comment]
When script deleted, edited, created, renamed, you should mark current state as dirty. Then check the dirty flag after **all** assets imported, and invoke `compileAndReload` if necessary.
You should also modify `compileAndReload` to change the ipc to send once compiled.

**Comment by jareguo** [comment]
Before reload scene, use these codes to stash the scene. After that you just need to reload the webview and the scene will reload itself.
```
    Async.waterfall(
        [
            dumpScene,
            stashScene,
        ],
        callback
    );
```
