### ISSUE TITLE
add start, update and destroy for fire script

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#94]
Since each mixin should have its own start, update and destroy. When we mixin a script, we should store their start, update, destroy in mixin's scope instead of in node scope, and trigger them one by one.

**Comment by jareguo** [comment]
start / lateUpdate 依赖于引擎本身的主循环，所以目前还没办法做。
cocos 没有 destroy 机制。用户要删除节点最好的方法是自己手工声明和调用 destroy，或者在 mixin 里定义 onEnter 和 onExit 这两个生命周期方法。
